version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: run tests
          command: |
            cd src
            npm run test-unit

      - run:
          name: Validate Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)
  

workflows:
  version: 2
  build-test-package:
    jobs:
      - build
            