version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src
            npm install

jobs:
  build:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV_OUTPUT_DIR: test-output
    steps:
      - checkout 
      - install_deps
      - run:
          name: run tests
          command: |
            cd src
            npm run test-unit

      - run:
          name: eslint
          command: |
            cd src
            npm run test-lint

      - run:
          name: Validate Coverage
          command: |
            bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-output

  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      APP_PORT: 4000
      NODE_ENV_OUTPUT_DIR: test-output
    steps:
      - checkout
      - install_deps
      - run:
          name: Run integration tests
          command: |
            cd src
            mkdir -p test-output
            npm run test-integration

      - store_test_results:
          path: test-output

  pack:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - run:
        mkdir -p dist
        zip -r dist/dist.zip <files> 
      - store_artifacts:
          path: ./
  

workflows:
  version: 2
  build-test-package:
    jobs:
      - build
      - integration-tests:
          requires:
            - build
      - pack:
          requires:
            - integration-tests
          filters:
            branches:
              only:
                - master